### ISSUE TITLE
1.79Mo RobotoFlex.ttf font for the demo page?

### ISSUE THREAD

**Issue by davidbgk** [clagnut/TODS#3]
I know it's a demo but still, it hurts 😅 

Maybe I miss the reason why it's not a woff2?

I can make a PR if it helps.

**Comment by clagnut** [comment]
Good point. Blame Google for not providing WOFFs as downloads - I just used the TTF download and forgot to update it. If you have the woff2 to hand and are up for creating a PR accordingly that would be great. Especially as i'm only using RobotoFlex to demo the grade axis.
